from langchain_core.prompts import ChatPromptTemplate
from datetime import datetime

# Define the standard footer content
NEWSLETTER_FOOTER = """
---
This newsletter is generated by an AI Agent. | © {current_year} AI Agent News
Stay updated on the latest in AI Agent Development!
"""

# Prompt for generating the full newsletter content
GENERATION_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a professional and engaging newsletter writer specializing in AI agent development. "
            "Your task is to transform a structured outline into a complete, well-written, and informative "
            "weekly newsletter **body content**. Adopt a clear, concise, and enthusiastic tone. "
            "Ensure accurate information transfer from the provided summaries."
            "You MUST use Markdown syntax throughout the entire newsletter body."
            "Strictly follow the heading hierarchy and article formatting as described below."
            "Crucially, provide ONLY the Markdown content for the newsletter body, with absolutely NO conversational filler or extra text outside the newsletter content itself. "
            "DO NOT include any introductory phrases like 'Here is the generated weekly AI Agent Development Newsletter content:' or extra markdown code fences (```) outside the main content."
            "All URLs from the outline MUST be used directly in the 'Read More' links. Do NOT modify URLs."
            "For article titles, output only the plain title. Do NOT add 'Read More' or any other text/characters next to article titles. Do NOT include trailing commas or other punctuation that isn't part of the actual title."
            "You MUST include the 'Summary:' prefix before each summary content, as a bullet point."
            "DO NOT generate the footer. The system will append the footer automatically. Your response should end just before the footer." # Explicitly remind to NOT generate footer
            "For each article, ensure there is ONLY ONE `[Read More](URL)` link, placed on a NEW LINE immediately after its summary, and it MUST use the exact URL provided in the outline."
            "Summaries should be concise, ideally 2-3 sentences, but accurately reflect the source summary."
            "Ensure the output is clean Markdown, ready for direct conversion to HTML."
            
            # specific instructions for Introduction and Conclusion length
            "For the **Introduction**, write 3-4 concise sentences that set the stage for the week's AI agent news, drawing from the provided `introduction_points`."
            "For the **Conclusion**, write 2-3 concise sentences that summarize key takeaways and offer a forward-looking perspective, drawing from `conclusion_points`."
            "For **Overall Trends**, provide a bulleted list of 2-3 trends, drawing from `overall_trends`."
            "**DO NOT format Introduction or Conclusion as bulleted lists.** Write them as flowing paragraphs." # Crucial: prevent bullet lists here
        ),
        (
            "human",
            "Please generate the weekly AI Agent Development Newsletter content based on the following outline. "
            "The current date is {current_date}. "
            "Here is the newsletter outline in JSON format:\n\n"
            "```json\n"
            "{newsletter_outline_json}\n" # Pass the whole outline JSON for context
            "```\n\n"
            "Generate the full newsletter content in Markdown format. "
            "Follow this exact structure and formatting for each section and article:\n\n"
            "## Introduction\n" # Always include this heading
            "{introduction_content}\n\n" # Placeholder for LLM-generated intro paragraph
            
            "**Section and Article Formatting for LLM to follow:**\n" 
            "- For each section in the outline, generate a `## Section Name` heading (e.g., `## New Frameworks & Tools`).\n"
            "- For each article within a section, generate a `### Article Title` heading. (CRITICAL: Just the plain title here, no URLs, commas, periods, or other extra text. Example: `### My Article Title`)\n"
            "- Immediately under the article title, generate a summary starting with a bullet point and 'Summary: ' (e.g., `- Summary: This is an article summary.`).\n"
            "- On a new line immediately after the summary, generate the clickable `[Read More](Article URL)` link. This link MUST be provided for every article using the exact URL from the outline. (Example: `[Read More](https://example.com/article)`) There should be ONLY ONE such link per article.\n"
            "- DO NOT include the 'Category' field in the article display.\n"
            "- If a summary is provided for an article in the outline, you MUST include it.\n\n"
            
            "## Conclusion\n" # Always include this heading
            "{conclusion_content}\n\n" # Placeholder for LLM-generated conclusion paragraph

            "**Overall Trends:**\n"
            "{overall_trends_content}\n\n" # Placeholder for LLM-generated trends list

            "Your entire response MUST be only the Markdown content, nothing else. DO NOT include any preamble or postamble text, or markdown fences outside of the content block. Ensure smooth flow and consistent formatting. Your response should end just before the footer."
        ),
    ]
)